branch-defaults:
  dev:
    environment: udagram-flosal-dev-dev
    group_suffix: null
  ops-3-auth:
    environment: udacity-c2-restapi-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
environment-defaults:
  udacity-c2-restapi-dev:
    branch: null
    repository: null
global:
  application_name: udagram-flosal-dev
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
